# Blog info
blog_name: b1ng0
slogan: We are all in the gutter, but some of us are looking at the stars. 
url: 

# Set avatar (Absolute url and relative url)
avatar: /images/head.jpg

# Set favicon
favicon: /images/favicon.ico

# For seo
keywords: b1ng0,sun1024,adminsun,python,php,Hexo主题,前端开发,nodejs,JavaScript,渗透测试,代码审计,web安全,CTF,SRC

home_nav:
  - name: Blog
    url: /archives
    target_blank: false #不在新页面打开
#  - name: Project
#    url: /project/
#    target_blank: false #在新页面打开
  - name: Github
    url: https://github.com/sun1024
    target_blank: true
  - name: Links
    url: /link/
    target_blank: false
  - name: About
    url: /about/
    target_blank: false
#  - name: Weibo
#    url: http://weibo.com/u/2351858273
#    target_blank: true

# config page nav
page_nav:
  - name: 博客
    url: /archives/
    target_blank: false # 不在新页面打开
  - name: 分类
    url: /category/
    target_blank: false
  - name: 标签
    url: /tag/
    target_blank: false
  - name: 友链
    url: /link/
    target_blank: false
  - name: 关于
    url: /about/
    target_blank: false
  - name: RSS
    url: /atom.xml
    target_blank: true # 在新页面打开
  - name: 搜索
    url: /search/
    target_blank: false # 在新页面打开

page_nav_style: CIRCLE  # CIRCLE|ROUND_RECT

# 面包屑
breadcrumb:
  isShow: true # true|fase

# 盒子
toolbox:
  isShow: false # true|fase
  text: 点我

search_slogan:
  isShow: true # true|fase
  text: Can you find the bug of world ~

link_slogan:
  isShow: true # true|fase
  text: 交换友链可以邮件 sunnanbin@gmail.com


# set backtop show or hide
backtop:
  home: false
  archive: false
  category: true
  tag: true
  post: true
  link: false
  about: false

donation:
  show: true
  btn_text: 支持一下
  tip: 扫一扫，支持sun1024
  items:
    - type: 微信
      text: 微信扫一扫
      imgUrl: /images/qr-wechat.png
    - type: 支付宝
      text: 支付宝扫一扫
      imgUrl: /images/qr-alipay.png




post:
  header_align: CENTER # LEFT|CENTER
  showToc: true # true|false
  showComments: true
  open_in_new_window: false
  show_prev_next: true

# =========================================================
# 个性化设置
# =========================================================

# Custom CSS style, 推荐把样式文件放在blog源码文件夹，而不是主题里面
#personal_style: /css/personal-style.css

# 这个值取决于你得背景图片是深色还是浅色，深色用dark，浅色用light
home_background_scheme: light # dark、light

# custom font-family 暂时只支持这3种英文字体，你可以完全自定义字体(看文档)
blog_name_font_familiy: calligraffittiregular
# blog_name_font_familiy: Lobster-Regular
# blog_name_font_familiy: PoiretOne-Regular

init_page_content: HOME_NAV  # HOME_NAV | POST


# =========================================================
# 第三方服务
# =========================================================
# Stats
google_analytics:
baidu_analytics: 57e94d016e201fba3603a8a2b0263af0

# Comment service
disqus_shortname: sun1024
# duoshuo_shortname: sun1024

# 不算子,文章访问量统计和显示
busuanzi: true

# =========================================================
# 页面内容设置
# =========================================================
about:
  - type: me
    icon: icon-user
    text_value:
    - " Cdut & Cqupt, 1996, Summer."
    - "左手coding, 右手hacking. 是代码菜鸡, 也是脚本小子."
    - "剑未配妥, 出门已是江湖..."
  - type: Github
    icon: icon-github
    text_key: Github
    text_value: "@sun1024"
    text_value_url: https://github.com/sun1024
#  - type: weibo
#    icon: icon-weibo
#    text_key: 微博
#    text_value: "@sun1024"
#    text_value_url: http://weibo.com/u/2351858273
  - type: mail
    icon: icon-mail
    text_key: Gmail
    text_value: "sunnanbin@gmail.com"
#  - type: location
#    icon: icon-location
#    text_value: 四川
  - type: mail
    icon: icon-test
    text_key: Hacktivity
    text_value: 
    - " Hacktivity："
    - " [CVE-2018-10073]  XSS in joyplus CMS"
    - " [CNVD-2018-17471] SQLi in emlsoft CMS"
link:
  - name: Drops
    info: 好好学习,天天向上
    url: http://119.29.64.123/WooyunDrops
    avatar: /images/head.jpg
  - name: 1000个PHP代码审计案例
    info: 什么都不会的时候，模仿是最快的学习方式
    url: http://119.29.64.123/1000php
    avatar: /images/head.jpg
  - name: Sue
    info: 一个小菜鸡。。。
    url: https://suwenbo.me/
    avatar: https://avatars0.githubusercontent.com/u/16314502?v=3&s=460
    
project:
  - type: personal
    name: none
    url: https://github.com/sun1024
    intro: To be continued
  # - type: company
  #   name: Fexo
  #   url: https://github.com/forsigner/fexo
  #   intro: A minimalist design theme for hexo
  